# Generated by Django 3.1.2 on 2020-10-29 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'recipes_categories',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('portion_portions', models.SmallIntegerField(default=1)),
                ('portion_size', models.PositiveIntegerField(default=0)),
                ('portion_unit', models.CharField(choices=[('gr', 'gr'), ('ml', 'ml'), ('un', 'un'), ('-', 'n/a')], default='-', max_length=5)),
                ('portion_detail', models.CharField(default='-', max_length=100)),
                ('favourite', models.BooleanField(default=False)),
                ('draft', models.BooleanField(default=False)),
                ('detail', models.TextField(default='-')),
                ('steps', models.TextField(default='-')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='recipes.recipecategory')),
            ],
            options={
                'verbose_name': 'recipe',
                'verbose_name_plural': 'recipes',
                'db_table': 'recipes',
                'ordering': ['category'],
                'get_latest_by': 'updated',
                'unique_together': {('title', 'category')},
                'index_together': {('title', 'category')},
            },
        ),
        migrations.CreateModel(
            name='IngredientInRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('unit', models.CharField(choices=[('gr', 'gr'), ('ml', 'ml'), ('un', 'un'), ('pinch', 'pinch'), ('dash', 'dash'), ('c/n', 'c/n')], default='c/n', max_length=5)),
                ('optional', models.BooleanField(default=False)),
                ('relevant', models.BooleanField(default=False)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='ingredients.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appears', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Ingredient in recipes',
                'verbose_name_plural': 'Ingredients in recipes',
                'db_table': 'recipes_ingredients_in_recipes',
                'ordering': ['recipe'],
                'unique_together': {('recipe', 'ingredient')},
                'index_together': {('recipe', 'ingredient')},
            },
        ),
    ]
